"use client";
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Icon, type IconName } from '@/components/icon';
type Stats = { pacientes_activos: number; citas_semana: number; leads_mes: number; zona_horaria: string; proximas: { id: string; fecha_hora: string; nombre_completo: string; modalidad: string }[] };
export function DashboardSummary() {
  const [data, setData] = useState<Stats | null>(null); const [error, setError] = useState(''); const [version, setVersion] = useState(0);
  useEffect(() => { const controller = new AbortController(); async function load() { try { const response = await fetch('/api/dashboard', { cache: 'no-store', signal: controller.signal }); const value = await response.json(); if (!response.ok) throw new Error(value.error); setData(value); setError(''); } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'No se pudo cargar el resumen.'); } } void load(); return () => controller.abort(); }, [version]);
  const cards: { key: keyof Pick<Stats, 'pacientes_activos' | 'citas_semana' | 'leads_mes'>; label: string; icon: IconName; note: string; color: string }[] = [
    { key: 'pacientes_activos', label: 'Pacientes activos', icon: 'users', note: 'En tratamiento activo', color: 'bg-teal-100 text-teal-800' },
    { key: 'citas_semana', label: 'Citas esta semana', icon: 'calendar', note: 'Lunes a domingo · sin canceladas', color: 'bg-blue-100 text-blue-800' },
    { key: 'leads_mes', label: 'Leads del mes', icon: 'spark', note: 'Nuevos pacientes desde captación o reservas', color: 'bg-amber-100 text-amber-900' },
  ];
  return <>{error && <p role="alert" className="mb-5 rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error} <button className="underline" onClick={() => setVersion(v => v + 1)}>Reintentar</button></p>}<div className="grid gap-5 lg:grid-cols-3">{cards.map(c => <section key={c.key} className="panel"><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-medium text-slate-500">{c.label}</h2><span className={`rounded-2xl p-3 ${c.color}`}><Icon name={c.icon} className="size-5" /></span></div><p className="mt-3 font-serif text-5xl text-slate-800">{data ? data[c.key] : '…'}</p><p className="mt-3 text-xs leading-5 text-slate-500">{c.note}</p></section>)}</div>{!data && !error && <p className="mt-4 text-sm text-slate-500" role="status">Cargando tus métricas…</p>}<section className="panel mt-7"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="font-serif text-2xl">Próximos encuentros</h2><Link href="/calendario" className="flex items-center gap-2 text-sm text-teal-700">Ver calendario<Icon name="arrow" className="size-4" /></Link></div>{data?.proximas.length ? <ul className="divide-y divide-slate-100">{data.proximas.map(a => <li key={a.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-medium">{a.nombre_completo}</p><time className="mt-1 block text-sm text-slate-500" dateTime={a.fecha_hora}>{new Date(a.fecha_hora).toLocaleString('es-CL', { timeZone: data.zona_horaria, dateStyle: 'medium', timeStyle: 'short' })}</time></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-800">{a.modalidad}</span></li>)}</ul> : <p className="py-8 text-center text-sm text-slate-500">{data ? 'No tienes citas próximas programadas.' : 'Tu agenda aparecerá aquí.'}</p>}</section><div className="mt-6 flex flex-wrap gap-3"><Link href="/pacientes" className="action">Gestionar pacientes<Icon name="users" className="size-4" /></Link><Link href="/marketing" className="secondary">Preparar contenido<Icon name="spark" className="size-4" /></Link></div>{data && <p className="mt-5 text-xs text-slate-500">Periodos calculados en {data.zona_horaria}. Los indicadores muestran exclusivamente tu consulta.</p>}</>;
}

