"use client";
import { useState } from 'react';
import { Icon } from '@/components/icon';
const questions = [
  { text: '¿Cuánto espacio has podido hacer para descansar esta semana?', options: ['El que necesitaba', 'Algo, aunque me gustaría más', 'Me ha costado encontrarlo'], topic: 'El descanso y tus límites' },
  { text: 'Cuando aparece una emoción difícil, ¿cómo te resulta ponerla en palabras?', options: ['Encuentro palabras con facilidad', 'A veces necesito tiempo', 'Me gustaría recibir acompañamiento'], topic: 'Cómo expresar lo que sientes' },
  { text: '¿Cómo describirías el trato que te das cuando algo no sale como esperabas?', options: ['Generalmente amable', 'Depende del momento', 'Suelo exigirme mucho'], topic: 'La relación contigo' },
  { text: '¿Tienes un espacio para conversar sobre lo que te preocupa?', options: ['Sí, y lo utilizo', 'A veces', 'Me gustaría encontrarlo'], topic: 'Tus espacios de apoyo' },
];
export function SelfAssessment() {
  const [answers, setAnswers] = useState<number[]>([]); const [step, setStep] = useState(0);
  const complete = step === questions.length;
  const topics = questions.filter((_, i) => answers[i] > 0);
  return <div className="rounded-[2rem] border border-teal-100 bg-white p-6 shadow-sm md:p-9">{complete ? <><span className="mb-5 inline-flex rounded-2xl bg-teal-100 p-3 text-teal-800"><Icon name="leaf" className="size-6" /></span><h3 className="font-serif text-3xl">Gracias por darte este momento.</h3><p className="mt-4 text-sm leading-7 text-slate-600">{topics.length ? 'A partir de tus respuestas, estos son algunos temas que podrías llevar a una conversación:' : 'Has identificado espacios de descanso y apoyo. Puedes seguir explorando qué te gustaría cuidar o comprender mejor.'}</p><ul className="my-5 space-y-3">{topics.map(q => <li key={q.topic} className="flex items-center gap-3 text-sm text-teal-800"><Icon name="check" className="size-4 shrink-0" />{q.topic}</li>)}</ul><p className="text-xs leading-6 text-slate-500">No hay una puntuación ni una interpretación clínica. Esta reflexión no sustituye una evaluación profesional. Tus respuestas no se guardan.</p><div className="mt-6 flex flex-wrap gap-3"><a href="#reservar" className="action">Quiero conversar<Icon name="arrow" className="size-4" /></a><button className="secondary" onClick={() => { setAnswers([]); setStep(0); }}>Volver a empezar</button></div></> : <><div className="flex items-center justify-between text-xs text-slate-500"><span>UNA PAUSA PARA TI</span><span>Pregunta {step + 1} de {questions.length}</span></div><div className="mt-4 flex gap-2" aria-hidden="true">{questions.map((_, i) => <span key={i} className={`h-1.5 flex-1 rounded-full ${i <= step ? 'bg-teal-500' : 'bg-slate-100'}`} />)}</div><fieldset className="mt-7"><legend className="font-serif text-2xl leading-snug text-teal-900 md:text-3xl">{questions[step].text}</legend><div className="mt-6 space-y-3">{questions[step].options.map((option, i) => <label key={option} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-4 text-sm transition-colors ${answers[step] === i ? 'border-teal-400 bg-teal-50' : 'border-slate-200 hover:bg-slate-50'}`}><input type="radio" name="respuesta" checked={answers[step] === i} onChange={() => setAnswers(previous => { const next = [...previous]; next[step] = i; return next; })} className="accent-teal-700" />{option}</label>)}</div></fieldset><div className="mt-7 flex items-center justify-between"><button className="text-sm text-slate-500 disabled:invisible" disabled={step === 0} onClick={() => setStep(step - 1)}>Anterior</button><button className="action" disabled={answers[step] === undefined} onClick={() => setStep(step + 1)}>{step === questions.length - 1 ? 'Ver mi reflexión' : 'Continuar'}<Icon name="arrow" className="size-4" /></button></div></>}</div>;
}
